apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
spec:
  containers:
    - name: web-server
      image: nginx
      volumeMounts:
        - mountPath: /var/share/nginx/html
          name: html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP
    - name: html-generator
      image: sm123tt/fortune
      command:
        - "/bin/fortuneloop.sh"
      envFrom:
        - configMapRef:
            name: fortune-config
      args: ["$(INTERVAL)"]
      volumeMounts:
        - mountPath: /var/htdocs
          name: html
  volumes:
    - name: html
      emptyDir: {}