apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-internal-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubia-internal
  template:
    metadata:
      labels:
        app: kubia-internal
    spec:
      containers:
        - name: kubia-internal
          image: sm123tt/kubia-internal
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP